-- =========================================================
-- PLANTVISION AI — SUPABASE DATABASE SCHEMA (FIXED & CLEAN)
-- Copy and paste all lines below into your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- =========================================================

-- 1. Create Profiles Table (Linked to Auth Users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  username TEXT UNIQUE,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS profiles_select_policy ON public.profiles;
CREATE POLICY profiles_select_policy
  ON public.profiles
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS profiles_insert_update_policy ON public.profiles;
CREATE POLICY profiles_insert_update_policy
  ON public.profiles
  FOR ALL
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);


-- 2. Create Scans History Table
CREATE TABLE IF NOT EXISTS public.scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  plant_id TEXT NOT NULL,
  plant_name TEXT NOT NULL,
  predicted_disease TEXT NOT NULL,
  pathogen TEXT,
  confidence NUMERIC NOT NULL,
  confidence_percent TEXT,
  is_healthy BOOLEAN NOT NULL,
  severity TEXT,
  image_thumbnail TEXT,
  symptoms JSONB DEFAULT '[]'::jsonb,
  remedies JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on Scans
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;

-- Scans Policies
DROP POLICY IF EXISTS scans_select_policy ON public.scans;
CREATE POLICY scans_select_policy
  ON public.scans
  FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS scans_insert_policy ON public.scans;
CREATE POLICY scans_insert_policy
  ON public.scans
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS scans_delete_policy ON public.scans;
CREATE POLICY scans_delete_policy
  ON public.scans
  FOR DELETE
  USING (auth.uid() = user_id);

-- Optional: Auto-create profile trigger on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS 
BEGIN
  INSERT INTO public.profiles (id, full_name, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Farmer'),
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
 LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
