-- =========================================================
-- PLANTVISION AI — SUPABASE DATABASE TABLES (COPY & RUN THIS)
-- Paste into Supabase SQL Editor:
-- https://supabase.com/dashboard/project/ypytalpbuzzutxrspmje/sql
-- =========================================================

-- 1. Users Table (Permanent User Accounts & Passwords)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable RLS for easy REST Anon API access
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;

-- 2. Scans History Table (Permanent Disease Scan Logs)
CREATE TABLE IF NOT EXISTS public.scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  plant TEXT NOT NULL,
  disease TEXT NOT NULL,
  confidence NUMERIC NOT NULL,
  severity TEXT NOT NULL,
  is_healthy BOOLEAN NOT NULL,
  image_path TEXT NOT NULL,
  symptoms_json TEXT,
  remedies_json TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable RLS for easy REST Anon API access
ALTER TABLE public.scans DISABLE ROW LEVEL SECURITY;

-- 3. Seed Default Demo User
INSERT INTO public.users (username, full_name, email, password_hash)
VALUES (
  'farmer_john',
  'Farmer John',
  'john@plantvision.ai',
  'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f'
)
ON CONFLICT (username) DO NOTHING;
