import io
import os
from datetime import datetime
from PIL import Image

def generate_pdf_report(scan_data: dict, leaf_image_path: str = None) -> bytes:
    "
    Generates a PDF report for a given plant disease scan.
    "
    try:
        from fpdf import FPDF
        
        class PlantReportPDF(FPDF):
            def header(self):
                self.set_font(Helvetica, B, 18)
                self.set_text_color(16, 120, 60) # Forest Green
                self.cell(0, 10, PlantVision AI - Plant Pathology Report, ln=True, align=C)
                self.set_font(Helvetica, I, 10)
                self.set_text_color(100, 100, 100)
                self.cell(0, 6, Automated Computer Vision Disease Diagnosis & Treatment Prescription, ln=True, align=C)
                self.set_draw_color(16, 120, 60)
                self.set_line_width(0.6)
                self.line(10, 28, 200, 28)
                self.ln(6)

            def footer(self):
                self.set_y(-15)
                self.set_font(Helvetica, I, 8)
                self.set_text_color(128, 128, 128)
                self.cell(0, 10, fGenerated by PlantVision AI System | Page {self.page_no()}, align=C)

        pdf = PlantReportPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Meta Info Table
        pdf.set_font(Helvetica, B, 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, 1. Scan & Diagnosis Overview, ln=True)
        
        pdf.set_font(Helvetica, ", 10)
 timestamp_str = scan_data.get(timestamp, datetime.now().strftime(%Y-%m-%d %H:%M:%S))
 
 pdf.cell(45, 6, fTarget Plant:, border=0)
 pdf.set_font(Helvetica, B, 10)
 pdf.cell(50, 6, f{scan_data.get('plant_name', 'Unknown')}, ln=False)
 pdf.set_font(Helvetica, , 10)
 pdf.cell(40, 6, fDate & Time:, border=0)
 pdf.cell(55, 6, f{timestamp_str}, ln=True)
 
 pdf.cell(45, 6, fBotanical Name:, border=0)
 pdf.set_font(Helvetica, I, 10)
 pdf.cell(50, 6, f{scan_data.get('scientific_name', 'N/A')}, ln=False)
 pdf.set_font(Helvetica, , 10)
 pdf.cell(40, 6, fConfidence Score:, border=0)
 pdf.set_font(Helvetica, B, 10)
 pdf.cell(55, 6, f{scan_data.get('confidence_percent', 'N/A')}, ln=True)
 
 pdf.set_font(Helvetica, , 10)
 pdf.cell(45, 6, fDetected Condition:, border=0)
 pdf.set_font(Helvetica, B, 11)
 disease_name = scan_data.get('predicted_disease', 'Unknown')
 is_healthy = scan_data.get('is_healthy', False)
 
 if is_healthy:
 pdf.set_text_color(16, 185, 129) # Emerald Green
 else:
 pdf.set_text_color(220, 38, 38) # Red
 
 pdf.cell(50, 6, f{disease_name}, ln=False)
 pdf.set_text_color(30, 41, 59)
 pdf.set_font(Helvetica, , 10)
 pdf.cell(40, 6, fSeverity Level:, border=0)
 pdf.set_font(Helvetica, B, 10)
 pdf.cell(55, 6, f{scan_data.get('severity', 'Moderate')}, ln=True)
 
 pdf.ln(4)
 
 # Symptoms Section
 pdf.set_font(Helvetica, B, 12)
 pdf.set_text_color(30, 41, 59)
 pdf.cell(0, 8, 2. Key Symptoms & Pathogen Details, ln=True)
 pdf.set_font(Helvetica, , 10)
 
 pathogen = scan_data.get(pathogen, N/A)
 if pathogen and pathogen != N/A:
 pdf.cell(0, 6, fPrimary Pathogen / Cause: {pathogen}, ln=True)
 
 symptoms = scan_data.get(symptoms, [])
 if symptoms:
 for s in symptoms:
 pdf.cell(8, 6, chr(149), align=R)
 pdf.multi_cell(0, 6, f {s})
 else:
 pdf.cell(0, 6, No severe symptoms or lesions detected on the foliage., ln=True)
 
 pdf.ln(4)
 
 # Recommendations Section
 pdf.set_font(Helvetica, B, 12)
 pdf.cell(0, 8, 3. Treatment & Management Prescription, ln=True)
 
 remedies = scan_data.get(remedies, {})
 organic = remedies.get(organic, [])
 chemical = remedies.get(chemical, [])
 prevention = remedies.get(prevention, [])
 
 # Organic
 pdf.set_font(Helvetica, B, 10)
 pdf.set_text_color(5, 150, 105)
 pdf.cell(0, 6, A. Eco-Friendly / Organic Remedies:, ln=True)
 pdf.set_font(Helvetica, , 9)
 pdf.set_text_color(30, 41, 59)
 for item in organic:
 pdf.cell(8, 5, chr(149), align=R)
 pdf.multi_cell(0, 5, f {item})
 
 pdf.ln(2)
 
 # Chemical
 pdf.set_font(Helvetica, B, 10)
 pdf.set_text_color(217, 119, 6)
 pdf.cell(0, 6, B. Recommended Chemical Fungicides & Spraying:, ln=True)
 pdf.set_font(Helvetica, , 9)
 pdf.set_text_color(30, 41, 59)
 for item in chemical:
 pdf.cell(8, 5, chr(149), align=R)
 pdf.multi_cell(0, 5, f {item})
 
 pdf.ln(2)
 
 # Prevention
 pdf.set_font(Helvetica, B, 10)
 pdf.set_text_color(37, 99, 235)
 pdf.cell(0, 6, C. Preventative Care & Cultural Practices:, ln=True)
 pdf.set_font(Helvetica, , 9)
 pdf.set_text_color(30, 41, 59)
 for item in prevention:
 pdf.cell(8, 5, chr(149), align=R)
 pdf.multi_cell(0, 5, f {item})
 
 pdf.ln(6)
 pdf.set_font(Helvetica, I, 8)
 pdf.set_text_color(120, 120, 120)
 pdf.cell(0, 6, * Note: Always verify chemical fungicide application with local agricultural extension guidelines., ln=True)

 return bytes(pdf.output())
 except Exception as e:
 print(f[ReportGenerator] PDF generation failed: {e})
 # Fallback text report
 report_text = f"PLANTVISION AI - PATHOLOGY REPORT
==========================================
Plant: {scan_data.get('plant_name')} ({scan_data.get('scientific_name')})
Condition: {scan_data.get('predicted_disease')}
Confidence: {scan_data.get('confidence_percent')}
Severity: {scan_data.get('severity')}
Date: {scan_data.get('timestamp')}

Symptoms:
{chr(10).join(['- ' + s for s in scan_data.get('symptoms', [])])}

Organic Remedies:
{chr(10).join(['- ' + s for s in scan_data.get('remedies', {}).get('organic', [])])}

Chemical Treatments:
{chr(10).join(['- ' + s for s in scan_data.get('remedies', {}).get('chemical', [])])}
"
 return report_text.encode(utf-8)
